modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="boat_signs"
version="1.0.2"
displayName="Boat Signs"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="ImTheBeemoPlush, MCreator"
description="Adds Swedish Boat Signs"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.boat_signs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration